package KieRule;
dialect "java"
import java.util.*;
global java.util.Collection generatedMenus
import com.javatechie.spring.drools.api.model.Order;

rule "HDFC"

when
orderObject : Order(cardType=="HDFC" && price>10000);
then
System.out.println(orderObject.getPrice());
end;

rule "ICICI"

when
orderObject : Order(cardType=="ICICI" && price>15000);
then
System.out.println(orderObject.getPrice());
end;

rule "DBS"

when
orderObject : Order(cardType=="DBS" && price>15000);
then
System.out.println(orderObject.getPrice());
end;